spring:
  application:
    name: hospitalappointmantsystem
  datasource:
    url: jdbc:postgresql://localhost:5433/hospitalappointmentsystem
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
    sql:
      init:
        platform: postgresql

spring.profiles.active: dev

server:
  port: 8082

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
